### ISSUE TITLE
Prometheus metric setup

### ISSUE THREAD

**Issue by adityagu0910** [bitsbeats/velero-pvc-watcher#1]
I am new to prometheus. Could you please help with instructions on how can we setup the metric and alert for the pvc watcher metric

**Comment by adityagu0910** [comment]
I  found the name of metrics getting generated - backupmonitor_missing

**Comment by Perfect-Web** [comment]
i this working ? i have deployed via helm but there are no `backupmonitor_missing` metrics ...
