### ISSUE TITLE
After backup restore stucking alert

### ISSUE THREAD

**Issue by ThoTischner** [bitsbeats/velero-pvc-watcher#2]
After restoring a backup there was a stuck alerting metric with owner "none".
Workaround: restart controller (Delete controller pod)

**Comment by prasenforu** [comment]
same issue, after pod annotated and volumes are backed up still alert ```backupmonitor_missing``` is showing. 

Same Workaround: restart controller (Delete controller pod).

**Comment by foosinn** [comment]
With the new release we changed the gathering quite a bit. I would assume that this also fixed the issue. This issue can be reopened if the changes did not if it.

@prasenforu: thanks for your feedback. feel free to report the issue if its still occurring.
